{{ if .Values.license }}
{{ if .Values.masterKeyRegenerator.enable }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-master-key-regenerator-setupfile
  labels: {{- include "master-key-regenerator-pod.labels" . | nindent 5 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  Setup.cfg: |-

    {{- include "ibmpemstandard.dbsetup" . | nindent 5 }}

{{ end }}
{{ end }}
