{{ if .Values.license }}
{{ if .Values.communitymanager.install }}
{{ if .Values.communitymanager.prod.enable }}
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: {{ .Release.Name }}-pcm-prod
  labels: {{- include "prodpcm-pod.labels" . | nindent 5 }}
spec:
  replicas: {{ .Values.communitymanager.prod.replicacount }}
  selector:
    matchLabels: {{- include "prodpcm.selectorLabels" . | nindent 7 }}
  template:
    metadata:
      labels: {{- include "prodpcm-pod.labels" . | nindent 9 }}
      annotations:
        productID: {{- include "ibmpem.metering.productId" . | indent 1 }}
        productMetric: {{- include "ibmpem.metering.productMetric" . | indent 1 }}
        productName: {{- include "ibmpem.metering.productName" . | indent 1 }}
        productVersion: {{- include "ibmpem.metering.productVersion" . | indent 1 }}
        productChargedContainers: {{- include "ibmpem.metering.productChargedContainers" . | indent 1 }}
        checksum/config: {{ include (print $.Template.BasePath "/prodpcmconfigmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      affinity: {{- include "ibmpem.affinity" . | nindent 9 }}
      volumes:
      #jars Resources
      {{ if .Values.volumeClaims.resources.enabled }}
      - name: {{ .Release.Name }}-resources
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-resources-pvc
      {{ end }}
      #setupfile
      - name: {{ .Release.Name }}-setupfile
        configMap:
            name: {{ .Release.Name }}-prodpcm-setupfile
      #archive
      {{ if .Values.communitymanager.prod.archive.enable }}
      - name: {{ .Release.Name }}-archive
        persistentVolumeClaim:
          claimName: {{ .Values.communitymanager.prod.archive.pvcname }}
      {{ end }}
      #logs
      {{ if .Values.volumeClaims.logs.enabled }}
      {{ if not .Values.setupfile.servers.enableConsoleLogs }}
      - name: {{ .Release.Name }}-logs
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-logs-pvc
      {{ end }}
      {{ end }}
      #app keystore
      - name: {{ .Release.Name }}-app-keystore
        secret:
           secretName: {{ .Release.Name }}-prodpcm-service
      #DB keystore
      {{ if .Values.communitymanager.prod.setupfile.spring.datasource.ssl.enabled }}
      {{ if .Values.communitymanager.prod.setupfile.spring.datasource.ssl.trustStoreSecret }}
      - name: {{ .Release.Name }}-pcmdb-keystore
        secret:
           secretName: {{ .Values.communitymanager.prod.setupfile.spring.datasource.ssl.trustStoreSecret }}
      {{ end }}
      {{ end }}
      #PEM key for scripts
      {{ if .Values.communitymanager.prod.setupfile.pem.remote.server.enabled }}
      {{ if .Values.communitymanager.prod.setupfile.pem.remote.server.pemKeySecret }}
      - name: {{ .Release.Name }}-pem-key
        secret:
           secretName: {{ .Values.communitymanager.prod.setupfile.pem.remote.server.pemKeySecret }}
      {{ end }}
      {{ end }}
      #PGP key
      {{ if .Values.communitymanager.prod.setupfile.file.archive.pgp.enabled }}
      {{ if .Values.communitymanager.prod.setupfile.file.archive.pgp.privateKeySecret }}
      - name: {{ .Release.Name }}-pgp-key
        secret:
           secretName: {{ .Values.communitymanager.prod.setupfile.file.archive.pgp.privateKeySecret }}
      {{ end }}
      {{ end }}
      #Seas truststore
      {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.ssp.enable }}
      {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.enabled }}
      {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.trust_store.secretName }}
      - name: {{ .Release.Name }}-seas-truststore
        secret:
           secretName: {{ .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.trust_store.secretName }}
      {{ end }}
      {{ end }}
      {{ end }}
      #Seas keystore
      {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.ssp.enable }}
      {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.enabled }}
      {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.key_store.secretName }}
      - name: {{ .Release.Name }}-seas-keystore
        secret:
           secretName: {{ .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.key_store.secretName }}
      {{ end }}
      {{ end }}
      {{ end }}
      {{ if .Values.communitymanager.prod.setupfile.oauth2.enable }}
      {{ if .Values.communitymanager.prod.setupfile.oauth2.client_secret }}
      - name: {{ .Release.Name }}-oauth2-client-secret
        secret:
           secretName: {{ .Values.communitymanager.prod.setupfile.oauth2.client_secret }}
      {{ end }}
      {{ end }}
      {{ if .Values.communitymanager.prod.setupfile.oauth2.enable }}
      {{ if .Values.communitymanager.prod.setupfile.oauth2.cmks }}
      - name: {{ .Release.Name }}-oauth2-cmks
        secret:
           secretName: {{ .Values.communitymanager.prod.setupfile.oauth2.cmks }}
      {{ end }}
      {{ end }}
      imagePullSecrets:
        - name: {{ .Values.communitymanager.image.pullSecret }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        {{ if  .Values.security.runAsUser }}
        runAsUser: {{ .Values.security.runAsUser | default "1011" }}
        {{ end }}
        runAsNonRoot: true
        supplementalGroups:
          {{- range $.Values.security.supplementalGroups }}
          - {{ . }}
          {{- end }}
        {{ if .Values.security.fsGroup }}
        fsGroup: {{ .Values.security.fsGroup | default "1011" }}
        {{ end }}
      containers:
        - name:  {{ .Release.Name }}-prod-pcm
          image: "{{ .Values.communitymanager.image.repository }}:{{ .Values.communitymanager.image.tag }}"
          imagePullPolicy: {{ .Values.communitymanager.image.pullPolicy }}
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            {{ if  .Values.security.runAsUser }}
            runAsUser: {{ .Values.security.runAsUser | default "1011" }}
            {{ end }}
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          resources: {{- toYaml .Values.communitymanager.prod.resources | nindent 13 }}
          volumeMounts:
            #jars
          {{ if .Values.volumeClaims.resources.enabled }}
          - name: {{ .Release.Name }}-resources
            mountPath: /opt/IBM/PCM/jars
            subPath: {{ .Values.volumeClaims.resources.subpath.pcm }}
          {{ end }}
          #setup[file
          - name: {{ .Release.Name }}-setupfile
            mountPath: /opt/IBM/config/application.yml
            subPath: application.yml
          #jvm options
          - name: {{ .Release.Name }}-setupfile
            mountPath: /opt/IBM/config/jvmoptions
            subPath: jvmoptions
          #archive location
          {{ if .Values.communitymanager.prod.archive.enable }}
          - name: {{ .Release.Name }}-archive
            mountPath: {{ .Values.communitymanager.prod.archive.path }}
          {{ end }}
          #logs
          {{ if .Values.volumeClaims.logs.enabled }}
          {{ if not .Values.setupfile.servers.enableConsoleLogs }}
          - name: {{ .Release.Name }}-logs
            mountPath: /opt/IBM/PCM/logs
            subPath: {{ .Values.volumeClaims.logs.subpath.pcmProd }}
          {{ end }}
          {{ end }}
          #app keystore
          - name: {{ .Release.Name }}-app-keystore
            mountPath: /opt/IBM/PCM/security/{{ .Release.Name }}-prodpcm-service
          #db keystore
          {{ if .Values.communitymanager.prod.setupfile.spring.datasource.ssl.enabled }}
          {{ if .Values.communitymanager.prod.setupfile.spring.datasource.ssl.trustStoreSecret }}
          - name: {{ .Release.Name }}-pcmdb-keystore
            mountPath: /opt/IBM/config/security/{{ .Values.communitymanager.prod.setupfile.spring.datasource.ssl.trust_store }}
            subPath: {{ .Values.communitymanager.prod.setupfile.spring.datasource.ssl.trust_store }}
          {{ end }}
          {{ end }}
          #pem key
          {{ if .Values.communitymanager.prod.setupfile.pem.remote.server.enabled }}
          {{ if .Values.communitymanager.prod.setupfile.pem.remote.server.pemKeySecret }}
          - name: {{ .Release.Name }}-pem-key
            mountPath: /opt/IBM/PCM/{{ .Values.communitymanager.prod.setupfile.pem.remote.server.pem_key }}
            subPath: {{ .Values.communitymanager.prod.setupfile.pem.remote.server.pem_key }}
          {{ end }}
          {{ end }}
          #PGP key
          {{ if .Values.communitymanager.prod.setupfile.file.archive.pgp.enabled }}
          {{ if .Values.communitymanager.prod.setupfile.file.archive.pgp.privateKeySecret }}
          - name: {{ .Release.Name }}-pgp-key
            mountPath: /opt/IBM/PCM/pgpkeys/{{ .Values.communitymanager.prod.setupfile.file.archive.pgp.private_key }}
            subPath: {{ .Values.communitymanager.prod.setupfile.file.archive.pgp.private_key }}
          {{ end }}
          {{ end }}
          #Seas truststore
          {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.ssp.enable }}
          {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.enabled }}
          {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.trust_store.secretName }}
          - name: {{ .Release.Name }}-seas-truststore
            mountPath: /opt/IBM/config/{{ .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.trust_store.name }}
            subPath: {{ .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.trust_store.name }}
          {{ end }}
          {{ end }}
          {{ end }}
          #Seas keystore
          {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.ssp.enable }}
          {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.enabled }}
          {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.key_store.secretName }}
          - name: {{ .Release.Name }}-seas-keystore
            mountPath: /opt/IBM/config/{{ .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.key_store.name }}
            subPath: {{ .Values.communitymanager.prod.setupfile.sso_ssp_seas.seas.ssl.key_store.name }}
          {{ end }}
          {{ end }}
          {{ end }}
          {{ if .Values.communitymanager.prod.setupfile.oauth2.enable }}
          {{ if .Values.communitymanager.prod.setupfile.oauth2.client_secret }}
          - name: {{ .Release.Name }}-oauth2-client-secret
            mountPath: /opt/IBM/config/{{ .Values.communitymanager.prod.setupfile.oauth2.client_secret }}
            subPath: {{ .Values.communitymanager.prod.setupfile.oauth2.client_secret }}
          {{ end }}
          {{ end }}
          {{ if .Values.communitymanager.prod.setupfile.oauth2.enable }}
          {{ if .Values.communitymanager.prod.setupfile.oauth2.cmks }}
          - name: {{ .Release.Name }}-oauth2-cmks
            mountPath: /opt/IBM/config/{{ .Values.communitymanager.prod.setupfile.oauth2.cmks }}
            subPath: {{ .Values.communitymanager.prod.setupfile.oauth2.cmks }}
          {{ end }}
          {{ end }}
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: {{ .Values.communitymanager.prod.readinessProbe.initialDelaySeconds | default 60 }}
            periodSeconds: {{ .Values.communitymanager.prod.readinessProbe.periodSeconds }}
          livenessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: {{ .Values.communitymanager.prod.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.communitymanager.prod.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.communitymanager.prod.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.communitymanager.prod.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.communitymanager.prod.livenessProbe.failureThreshold }}
          ports:
            - containerPort: 9080
              protocol: "TCP"
          env:
            - name: NODE_IP
              value: localhost
            - name: NODE_PORT
              value: "9080"
            - name: SERVICE_NAME
              value: {{ .Release.Name }}-prodpcm-service
            {{ if .Values.communitymanager.prod.setupfile.sso_ssp_seas.enable }}
            - name: APP
              value: ocp-sso-ssp-seas
            {{ else }}
            - name: APP
              value: ocp-community
            {{ end }}
            {{ if .Values.setupfile.servers.enableConsoleLogs }}
            - name: CONSOLE_LOGGING
              value: "true"
            {{ else }}
            - name: CONSOLE_LOGGING
              value: "false"
            {{ end }}
            - name: LOGGER_LEVEL
              value: {{ .Values.communitymanager.prod.setupfile.loggerLevel }}
          envFrom:
          {{ if .Values.communitymanager.prod.setupfile.cm.cmSecret }}
          - secretRef:
              name: {{ .Values.communitymanager.prod.setupfile.cm.cmSecret }}
          {{ end }}
{{ end }}
{{ end }}
{{ end }}
